spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/tinder
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: o5046821854@gmail.com
    password: pwkheqwgxrgsdfdb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
